#!/usr/bin/env bash
#
#  author  : Jeong Han Lee
#  email   : jeonghan.lee@gmail.com
#  date    : Saturday, June 27 16:45:01 PDT 2020 
#  version : 0.0.1

declare -gr SC_SCRIPT="$(realpath "$0")"
declare -gr SC_SCRIPTNAME=${0##*/}
declare -gr SC_TOP="${SC_SCRIPT%/*}"
declare -gr LOGDATE="$(date +%y%m%d%H)"



function pushd { builtin pushd "$@" > /dev/null; }
function popd  { builtin popd  "$@" > /dev/null; }


SRC_TOP=${SC_TOP}/../../

pushd ${SRC_TOP}

docker build . --file docker/Dockerfile --tags=jeonghanlee/channelfinder:${LOGDATE}

popd

