#!/usr/bin/env bash
#
#  author  : Jeong Han Lee
#  email   : jeonghan.lee@gmail.com
#  date    : Saturday, June 27 16:45:01 PDT 2020 
#  version : 0.0.1

## Still not clear how to handle target image name well..

##
declare -gr LOGDATE="$(date +%y%m%d%H%M)"

source_image_name="$1"; shift;
target_image_name="jeonghanlee/${source_image_name}-${LOGDATE}"


if [ -z "${source_image_name}" ]; then
	echo "">&2
        echo "usage: $0 <source_image_name>" >&2
        echo >&2
        exit 0
fi


# docker tag ${source_image_name} ${target_image_name}
# docker push ${target_image_name}


								   
