---
name: macOS build

on:
  push:
    branches: [master]
    paths-ignores:
      - '**.md'
      - '.github/workflows/build.yml'

  pull_request:
    branches: [master]

jobs:
  macOS12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: |
          brew install tree wget curl bash jq coreutils
      - name : Check JAVA Environment
        run: |
          which java
          which mvn
          tree -L 2 /usr/local/opt/
          tree -L 2 /usr/local/Cellar/
      - name: ES Configuration
        run: |
          make init
          make install.esmac
          make conf.macos
          make conf.esmac
      - name: CF Configuration and build
        run: |
          make conf
          make vars
          make build
          make cf_install
      - name: Environment Check
        run: make exist
          
