---
name: macOS build

on:
  push:
    branches: [master]
    paths-ignores:
      - '**.md'
      - '.github/workflows/build.yml'

  pull_request:
    branches: [master]

jobs:
  macOS12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: |
          brew install tree wget curl bash jq coreutils
      - name : Check JAVA Environment
        run: |
          which java
          which mvn
          tree -L 2 /usr/local/opt/
          tree -L 2 /usr/local/Cellar/
      - name: ES Configuration
        run: |
          make init
          make install.esmac
          make conf.macos
          make conf.esmac
      - name: CF Configuration and build
        run: |
          make conf
          make build
      - name: Environment Check
        run: |
          make start.esmac
          sleep 10 
          make status.esmac
          make mapping
          make mapping.verify
          make demo
          sleep 10
          bash scripts/cf_queries.bash get tags foo
          bash scripts/cf_queries.bash put tags foo scripts/tag_foo.json
          bash scripts/cf_queries.bash get tags foo

