---
name: Ubuntu Latest

on:
  push:
    branches: [ master ]
    paths-ignores:
      - '*.md'
      - 'examples/*.bash'

  pull_request:
    branches: [ master ]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18.0.2'
    - run: sudo apt-get install make tree git 
    - run: |
        which java
        which mvn
    - run: |
        make init
        make vars
        make github.conf
        make conf
    - run: |
        make build
        make install
    - run: make exist
     
